[package]
name = "actix-lua-hot-reload"
version = "0.1.0"
authors = ["Poga Po <poga.bahamut@gmail.com>"]

[dependencies]
actix = "0.10"
futures = "0.3"
lazy_static = "1.1.0"

actix-lua = { path = "../.." }
